CREATE TABLE IF NOT EXISTS `holster` (
	`playerid` INT UNSIGNED NOT NULL,
	`itemid`   INT UNSIGNED NOT NULL DEFAULT 0,
	`param`    INT UNSIGNED NOT NULL DEFAULT 0,
	`pos_x`    FLOAT NOT NULL DEFAULT 0.08,
	`pos_y`    FLOAT NOT NULL DEFAULT 0.07,
	`pos_z`    FLOAT NOT NULL DEFAULT -0.10,
	`rot_x`    FLOAT NOT NULL DEFAULT 0.0,
	`rot_y`    FLOAT NOT NULL DEFAULT 0.0,
	`rot_z`    FLOAT NOT NULL DEFAULT 0.0,
	`sc_x`     FLOAT NOT NULL DEFAULT 0.8,
	`sc_y`     FLOAT NOT NULL DEFAULT 0.8,
	`sc_z`     FLOAT NOT NULL DEFAULT 0.8,
	PRIMARY KEY (`playerid`)
);
